apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: azure-vote
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: ref #local-c1
            url: https://kubernetes.default.svc
          - cluster: ppd #local-c2
            url: https://192.168.1.68:8443
  template:
    metadata:
      name: '{{cluster}}-azure-vote'
    spec:
      project: default
      source:
        repoURL: https://github.com/brahimsayah/argocd-poc.git
        targetRevision: HEAD
        path: envs/{{cluster}}/azure-vote
      destination:
        server: '{{url}}'
        namespace: dev
